
#ifndef _STRATO_CONFIG_H_
#define _STRATO_CONFIG_H_

#define RF_CS_PIN 8
#define RF_IRQ_PIN 20
#define RF_RST_PIN 21

#define SENSORS_INTERVAL 1000 //ms
#define LORAWAN_INTERVAL 60 //s

#define ADS1115_ADDR 0x4A
#define QMC5883_ADDR 0x0D

#define VOLTAGE_DIVIDER_A0_R1 20
#define VOLTAGE_DIVIDER_A0_R2 51
#define VOLTAGE_DIVIDER_A1_R1 51
#define VOLTAGE_DIVIDER_A1_R2 51
#define VOLTAGE_DIVIDER_A2_R1
#define VOLTAGE_DIVIDER_A2_R2
#define VOLTAGE_DIVIDER_A3_R1
#define VOLTAGE_DIVIDER_A3_R2


#endif // _STRATO_CONFIG_H_